### ISSUE TITLE
視覺畫面令人驚艷

### ISSUE THREAD

**Issue by Tommy0901** [kim1037/AC-expense-tracker#1]
Kim 你好, 我是 AC 後端的學生 Tommy

有先把你的專案 clone 下來玩看看，發現你做的畫面很漂亮也好用心~!!

**Comment by kim1037** [comment]
Hi Tommy,

謝謝你寫信告訴我，希望我之前做的作業對你學習有幫助，加油喔！


Best regards,
Kim Hong


Tommy ***@***.***>於 2024年3月25日 週一，下午5:12寫道：

**Comment by Tommy0901** [comment]
Greetings Kim,

目前正在作品集準備的階段，想詢問妳是否會介意我把前端畫面(Views)的內容，當成個人的模板使用?

謝謝~

**Comment by kim1037** [comment]
嗨Tommy,

不好意思工作繁忙晚回覆你，請隨意拿去使用，我很榮幸可以能夠幫助到你，祝你求職順利唷！


Best regards,
Kim Hong


Tommy ***@***.***>於 2024年5月2日 週四，上午8:29寫道：
